/*
 * Automatically generated from test.rpc
 * by event_rpcgen.py/0.1.  DO NOT EDIT THIS FILE.
 */

#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <event2/event-config.h>
#include <event2/event.h>
#include <event2/buffer.h>
#include <event2/tag.h>

#ifdef _EVENT___func__
#define __func__ _EVENT___func__
#endif


#include "test.gen.h"

void event_warn(const char *fmt, ...);
void event_warnx(const char *fmt, ...);


/*
 * Implementation of ping
 */

static struct ping_access_ __ping_base = {
  ping_version_assign,
  ping_version_get,
  ping_ip_assign,
  ping_ip_get,
  ping_port_assign,
  ping_port_get,
};

struct ping *
ping_new(void)
{
  return ping_new_with_arg(NULL);
}

struct ping *
ping_new_with_arg(void *unused)
{
  struct ping *tmp;
  if ((tmp = malloc(sizeof(struct ping))) == NULL) {
    event_warn("%s: malloc", __func__);
    return (NULL);
  }
  tmp->base = &__ping_base;

  tmp->version_data = 0;
  tmp->version_set = 0;

  tmp->ip_data = NULL;
  tmp->ip_set = 0;

  tmp->port_data = 0;
  tmp->port_set = 0;

  return (tmp);
}




int
ping_version_assign(struct ping *msg, const ev_uint32_t value)
{
  msg->version_set = 1;
  msg->version_data = value;
  return (0);
}

int
ping_ip_assign(struct ping *msg,
    const char * value)
{
  if (msg->ip_data != NULL)
    free(msg->ip_data);
  if ((msg->ip_data = strdup(value)) == NULL)
    return (-1);
  msg->ip_set = 1;
  return (0);
}

int
ping_port_assign(struct ping *msg, const ev_uint32_t value)
{
  msg->port_set = 1;
  msg->port_data = value;
  return (0);
}

int
ping_version_get(struct ping *msg, ev_uint32_t *value)
{
  if (msg->version_set != 1)
    return (-1);
  *value = msg->version_data;
  return (0);
}

int
ping_ip_get(struct ping *msg, char * *value)
{
  if (msg->ip_set != 1)
    return (-1);
  *value = msg->ip_data;
  return (0);
}

int
ping_port_get(struct ping *msg, ev_uint32_t *value)
{
  if (msg->port_set != 1)
    return (-1);
  *value = msg->port_data;
  return (0);
}

void
ping_clear(struct ping *tmp)
{
  tmp->version_set = 0;
  if (tmp->ip_set == 1) {
    free(tmp->ip_data);
    tmp->ip_data = NULL;
    tmp->ip_set = 0;
  }
  tmp->port_set = 0;
}

void
ping_free(struct ping *tmp)
{
  if (tmp->ip_data != NULL)
      free (tmp->ip_data);
  free(tmp);
}

void
ping_marshal(struct evbuffer *evbuf, const struct ping *tmp){
  evtag_marshal_int(evbuf, PING_VERSION, tmp->version_data);
  evtag_marshal_string(evbuf, PING_IP, tmp->ip_data);
  evtag_marshal_int(evbuf, PING_PORT, tmp->port_data);
}

int
ping_unmarshal(struct ping *tmp,  struct evbuffer *evbuf)
{
  ev_uint32_t tag;
  while (evbuffer_get_length(evbuf) > 0) {
    if (evtag_peek(evbuf, &tag) == -1)
      return (-1);
    switch (tag) {

      case PING_VERSION:

        if (tmp->version_set)
          return (-1);
        if (evtag_unmarshal_int(evbuf, PING_VERSION, &tmp->version_data) == -1) {
          event_warnx("%s: failed to unmarshal version", __func__);
          return (-1);
        }
        tmp->version_set = 1;
        break;

      case PING_IP:

        if (tmp->ip_set)
          return (-1);
        if (evtag_unmarshal_string(evbuf, PING_IP, &tmp->ip_data) == -1) {
          event_warnx("%s: failed to unmarshal ip", __func__);
          return (-1);
        }
        tmp->ip_set = 1;
        break;

      case PING_PORT:

        if (tmp->port_set)
          return (-1);
        if (evtag_unmarshal_int(evbuf, PING_PORT, &tmp->port_data) == -1) {
          event_warnx("%s: failed to unmarshal port", __func__);
          return (-1);
        }
        tmp->port_set = 1;
        break;

      default:
        return -1;
    }
  }

  if (ping_complete(tmp) == -1)
    return (-1);
  return (0);
}

int
ping_complete(struct ping *msg)
{
  if (!msg->version_set)
    return (-1);
  if (!msg->ip_set)
    return (-1);
  if (!msg->port_set)
    return (-1);
  return (0);
}

int
evtag_unmarshal_ping(struct evbuffer *evbuf, ev_uint32_t need_tag, struct ping *msg)
{
  ev_uint32_t tag;
  int res = -1;

  struct evbuffer *tmp = evbuffer_new();

  if (evtag_unmarshal(evbuf, &tag, tmp) == -1 || tag != need_tag)
    goto error;

  if (ping_unmarshal(msg, tmp) == -1)
    goto error;

  res = 0;

 error:
  evbuffer_free(tmp);
  return (res);
}

void
evtag_marshal_ping(struct evbuffer *evbuf, ev_uint32_t tag, const struct ping *msg)
{
  struct evbuffer *_buf = evbuffer_new();
  assert(_buf != NULL);
  ping_marshal(_buf, msg);
  evtag_marshal_buffer(evbuf, tag, _buf);
   evbuffer_free(_buf);
}

/*
 * Implementation of machine
 */

static struct machine_access_ __machine_base = {
  machine_uuid_assign,
  machine_uuid_get,
  machine_ip_assign,
  machine_ip_get,
  machine_port_assign,
  machine_port_get,
  machine_type_assign,
  machine_type_get,
};

struct machine *
machine_new(void)
{
  return machine_new_with_arg(NULL);
}

struct machine *
machine_new_with_arg(void *unused)
{
  struct machine *tmp;
  if ((tmp = malloc(sizeof(struct machine))) == NULL) {
    event_warn("%s: malloc", __func__);
    return (NULL);
  }
  tmp->base = &__machine_base;

  tmp->uuid_data = 0;
  tmp->uuid_set = 0;

  tmp->ip_data = NULL;
  tmp->ip_set = 0;

  tmp->port_data = 0;
  tmp->port_set = 0;

  tmp->type_data = 0;
  tmp->type_set = 0;

  return (tmp);
}





int
machine_uuid_assign(struct machine *msg, const ev_uint32_t value)
{
  msg->uuid_set = 1;
  msg->uuid_data = value;
  return (0);
}

int
machine_ip_assign(struct machine *msg,
    const char * value)
{
  if (msg->ip_data != NULL)
    free(msg->ip_data);
  if ((msg->ip_data = strdup(value)) == NULL)
    return (-1);
  msg->ip_set = 1;
  return (0);
}

int
machine_port_assign(struct machine *msg, const ev_uint32_t value)
{
  msg->port_set = 1;
  msg->port_data = value;
  return (0);
}

int
machine_type_assign(struct machine *msg, const ev_uint32_t value)
{
  msg->type_set = 1;
  msg->type_data = value;
  return (0);
}

int
machine_uuid_get(struct machine *msg, ev_uint32_t *value)
{
  if (msg->uuid_set != 1)
    return (-1);
  *value = msg->uuid_data;
  return (0);
}

int
machine_ip_get(struct machine *msg, char * *value)
{
  if (msg->ip_set != 1)
    return (-1);
  *value = msg->ip_data;
  return (0);
}

int
machine_port_get(struct machine *msg, ev_uint32_t *value)
{
  if (msg->port_set != 1)
    return (-1);
  *value = msg->port_data;
  return (0);
}

int
machine_type_get(struct machine *msg, ev_uint32_t *value)
{
  if (msg->type_set != 1)
    return (-1);
  *value = msg->type_data;
  return (0);
}

void
machine_clear(struct machine *tmp)
{
  tmp->uuid_set = 0;
  if (tmp->ip_set == 1) {
    free(tmp->ip_data);
    tmp->ip_data = NULL;
    tmp->ip_set = 0;
  }
  tmp->port_set = 0;
  tmp->type_set = 0;
}

void
machine_free(struct machine *tmp)
{
  if (tmp->ip_data != NULL)
      free (tmp->ip_data);
  free(tmp);
}

void
machine_marshal(struct evbuffer *evbuf, const struct machine *tmp){
  evtag_marshal_int(evbuf, MACHINE_UUID, tmp->uuid_data);
  evtag_marshal_string(evbuf, MACHINE_IP, tmp->ip_data);
  evtag_marshal_int(evbuf, MACHINE_PORT, tmp->port_data);
  evtag_marshal_int(evbuf, MACHINE_TYPE, tmp->type_data);
}

int
machine_unmarshal(struct machine *tmp,  struct evbuffer *evbuf)
{
  ev_uint32_t tag;
  while (evbuffer_get_length(evbuf) > 0) {
    if (evtag_peek(evbuf, &tag) == -1)
      return (-1);
    switch (tag) {

      case MACHINE_UUID:

        if (tmp->uuid_set)
          return (-1);
        if (evtag_unmarshal_int(evbuf, MACHINE_UUID, &tmp->uuid_data) == -1) {
          event_warnx("%s: failed to unmarshal uuid", __func__);
          return (-1);
        }
        tmp->uuid_set = 1;
        break;

      case MACHINE_IP:

        if (tmp->ip_set)
          return (-1);
        if (evtag_unmarshal_string(evbuf, MACHINE_IP, &tmp->ip_data) == -1) {
          event_warnx("%s: failed to unmarshal ip", __func__);
          return (-1);
        }
        tmp->ip_set = 1;
        break;

      case MACHINE_PORT:

        if (tmp->port_set)
          return (-1);
        if (evtag_unmarshal_int(evbuf, MACHINE_PORT, &tmp->port_data) == -1) {
          event_warnx("%s: failed to unmarshal port", __func__);
          return (-1);
        }
        tmp->port_set = 1;
        break;

      case MACHINE_TYPE:

        if (tmp->type_set)
          return (-1);
        if (evtag_unmarshal_int(evbuf, MACHINE_TYPE, &tmp->type_data) == -1) {
          event_warnx("%s: failed to unmarshal type", __func__);
          return (-1);
        }
        tmp->type_set = 1;
        break;

      default:
        return -1;
    }
  }

  if (machine_complete(tmp) == -1)
    return (-1);
  return (0);
}

int
machine_complete(struct machine *msg)
{
  if (!msg->uuid_set)
    return (-1);
  if (!msg->ip_set)
    return (-1);
  if (!msg->port_set)
    return (-1);
  if (!msg->type_set)
    return (-1);
  return (0);
}

int
evtag_unmarshal_machine(struct evbuffer *evbuf, ev_uint32_t need_tag, struct machine *msg)
{
  ev_uint32_t tag;
  int res = -1;

  struct evbuffer *tmp = evbuffer_new();

  if (evtag_unmarshal(evbuf, &tag, tmp) == -1 || tag != need_tag)
    goto error;

  if (machine_unmarshal(msg, tmp) == -1)
    goto error;

  res = 0;

 error:
  evbuffer_free(tmp);
  return (res);
}

void
evtag_marshal_machine(struct evbuffer *evbuf, ev_uint32_t tag, const struct machine *msg)
{
  struct evbuffer *_buf = evbuffer_new();
  assert(_buf != NULL);
  machine_marshal(_buf, msg);
  evtag_marshal_buffer(evbuf, tag, _buf);
   evbuffer_free(_buf);
}

/*
 * Implementation of pong
 */

static struct pong_access_ __pong_base = {
  pong_version_assign,
  pong_version_get,
  pong_xx_assign,
  pong_xx_get,
};

struct pong *
pong_new(void)
{
  return pong_new_with_arg(NULL);
}

struct pong *
pong_new_with_arg(void *unused)
{
  struct pong *tmp;
  if ((tmp = malloc(sizeof(struct pong))) == NULL) {
    event_warn("%s: malloc", __func__);
    return (NULL);
  }
  tmp->base = &__pong_base;

  tmp->version_data = 0;
  tmp->version_set = 0;

  tmp->xx_data = 0;
  tmp->xx_set = 0;

  return (tmp);
}



int
pong_version_assign(struct pong *msg, const ev_uint32_t value)
{
  msg->version_set = 1;
  msg->version_data = value;
  return (0);
}

int
pong_xx_assign(struct pong *msg, const ev_uint32_t value)
{
  msg->xx_set = 1;
  msg->xx_data = value;
  return (0);
}

int
pong_version_get(struct pong *msg, ev_uint32_t *value)
{
  if (msg->version_set != 1)
    return (-1);
  *value = msg->version_data;
  return (0);
}

int
pong_xx_get(struct pong *msg, ev_uint32_t *value)
{
  if (msg->xx_set != 1)
    return (-1);
  *value = msg->xx_data;
  return (0);
}

void
pong_clear(struct pong *tmp)
{
  tmp->version_set = 0;
  tmp->xx_set = 0;
}

void
pong_free(struct pong *tmp)
{
  free(tmp);
}

void
pong_marshal(struct evbuffer *evbuf, const struct pong *tmp){
  evtag_marshal_int(evbuf, PONG_VERSION, tmp->version_data);
  evtag_marshal_int(evbuf, PONG_XX, tmp->xx_data);
}

int
pong_unmarshal(struct pong *tmp,  struct evbuffer *evbuf)
{
  ev_uint32_t tag;
  while (evbuffer_get_length(evbuf) > 0) {
    if (evtag_peek(evbuf, &tag) == -1)
      return (-1);
    switch (tag) {

      case PONG_VERSION:

        if (tmp->version_set)
          return (-1);
        if (evtag_unmarshal_int(evbuf, PONG_VERSION, &tmp->version_data) == -1) {
          event_warnx("%s: failed to unmarshal version", __func__);
          return (-1);
        }
        tmp->version_set = 1;
        break;

      case PONG_XX:

        if (tmp->xx_set)
          return (-1);
        if (evtag_unmarshal_int(evbuf, PONG_XX, &tmp->xx_data) == -1) {
          event_warnx("%s: failed to unmarshal xx", __func__);
          return (-1);
        }
        tmp->xx_set = 1;
        break;

      default:
        return -1;
    }
  }

  if (pong_complete(tmp) == -1)
    return (-1);
  return (0);
}

int
pong_complete(struct pong *msg)
{
  if (!msg->version_set)
    return (-1);
  if (!msg->xx_set)
    return (-1);
  return (0);
}

int
evtag_unmarshal_pong(struct evbuffer *evbuf, ev_uint32_t need_tag, struct pong *msg)
{
  ev_uint32_t tag;
  int res = -1;

  struct evbuffer *tmp = evbuffer_new();

  if (evtag_unmarshal(evbuf, &tag, tmp) == -1 || tag != need_tag)
    goto error;

  if (pong_unmarshal(msg, tmp) == -1)
    goto error;

  res = 0;

 error:
  evbuffer_free(tmp);
  return (res);
}

void
evtag_marshal_pong(struct evbuffer *evbuf, ev_uint32_t tag, const struct pong *msg)
{
  struct evbuffer *_buf = evbuffer_new();
  assert(_buf != NULL);
  pong_marshal(_buf, msg);
  evtag_marshal_buffer(evbuf, tag, _buf);
   evbuffer_free(_buf);
}

